name: Automating Create Pull Request

on:
  push:

jobs:
  auto-pull-request:
    name: Create Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Commit Tag
        id: check-tag
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^[a-z]{1,10}-pr:[[:space:]].+ ]]; then
              echo ::set-output name=match::true
          fi
          
      - name: Create Hotfix PR Action
        if: steps.check-tag.outputs.match == 'true'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "hotfix/"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_TITLE: ${{ format('[HOTFIX] {0}', github.ref_name) }}
          
      - name: Create Feature PR Action
        if: steps.check-tag.outputs.match == 'true'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feature/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ format('[FEATURE] by {0}', github.actor) }}
          PULL_REQUEST_BODY: "변경 사항을 기록해 주세요👣"
          
      - name: Create Bugfix PR Action
        if: steps.check-tag.outputs.match == 'true'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "bugfix/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ format('[BUGFIX] by {0}', github.actor) }}      
          PULL_REQUEST_BODY: "수정 사항을 기록해 주세요😎"
      
      - name: Create Refactor PR Action
        if: steps.check-tag.outputs.match == 'true'
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "refactor/"
          PULL_REQUEST_BRANCH: "develop"
          PULL_REQUEST_TITLE: ${{ format('[REFACTOR] by {0}', github.actor) }}
          PULL_REQUEST_BODY: "리팩토링 내용을 기록해 주세요👀"
          
          
          
